#!/bin/bash

#Semi-Automatic packaging of the i9506 FireWork Kernel into flashable zip files
#Copyright 2015 Kiffmet@XDA-Developers
#You are free to redistribute, bundle and modify this if you mention me in the copyrights of the
#project you used this in. All changes to this have to be made open source under the same condidion.

rm -R temp/newzip
rm -R temp/boot.img
rm -R temp/ramdisk-new.cpio.gz
rm -R temp/ramdisk
rm -R temp/split_img

rm output/*
